rm -rf ffmpeg-4.3.2/config.asm
rm -rf ffmpeg-4.3.2/config.h
rm -rf ffmpeg-4.3.2/doc/config.texi
rm -rf ffmpeg-4.3.2/ffbuild/.config
rm -rf ffmpeg-4.3.2/ffbuild/config.fate
rm -rf ffmpeg-4.3.2/ffbuild/config.log
rm -rf ffmpeg-4.3.2/ffbuild/config.mak
rm -rf ffmpeg-4.3.2/ffbuild/config.sh
rm -rf ffmpeg-4.3.2/libavcodec/bsf_list.c
rm -rf ffmpeg-4.3.2/libavcodec/codec_list.c
rm -rf ffmpeg-4.3.2/libavcodec/parser_list.c
rm -rf ffmpeg-4.3.2/libavdevice/indev_list.c
rm -rf ffmpeg-4.3.2/libavdevice/outdev_list.c
rm -rf ffmpeg-4.3.2/libavfilter/filter_list.c
rm -rf ffmpeg-4.3.2/libavformat/demuxer_list.c
rm -rf ffmpeg-4.3.2/libavformat/muxer_list.c
rm -rf ffmpeg-4.3.2/libavformat/protocol_list.c
rm -rf ffmpeg-4.3.2/libavutil/avconfig.h
rm -rf ffmpeg-4.3.2/libavutil/ffversion.h
